backend:
  name: github
  repo: furqaanhere/furqaanhere.github.io

media_folder: "images"
public_folder: "/images"

media_library:
  name: "uploadcare"

collections:
  - name: "site"
    label: "Website Content"
    files:
      - file: "content.json"
        label: "Homepage"
        name: "home"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
