backend:
  name: github
  repo: furqaanhere/furqaanhere.github.io

collections:
  - name: "site"
    label: "Content"
    files:
      - file: "content.json"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
